### PR TITLE
merge project d2 updates

### PR DESCRIPTION
**Pull request by lhe2**
issues addressed from https://github.com/How-to-Learn-to-Code/Rclass-DataScience/issues/10:

- [x] created separate instructor version
- [x] fixed image paths under "Example figures" for each dataset in the main doc (hopefully???)
- [ ] still need to finalise locations of external documents for this lesson and then update the wording in the doc (look for `//TODO` in main doc)

### CODE REVIEW

**Review by jtlandis — COMMENTED** [review]
I like how things were changed in the formatting of the questions. I agree that we need to finalize the location of the data. If they have gone through the previous lecture, then they should have a github account and will be able to clone out this repo to access the data.

Aside from fixing the file paths on the class8.qmd, there is one thing I'll comment on that will surely break. The `example-*.qmd` files all read data from a path on @lhe2's system. If the students try and run this script, they will surely be met with an error.

Given the preamble of the documents this maybe fine, as it doesn't explicitly state the file path may be an issue but notes the script may not work "out of the box". Alternatively, we could consider using the [here](https://here.r-lib.org/) package so that file paths are relative to the Rproject root.

**Comment by lhe2** [comment]
re: data paths on the `example-.qmd`, oh yes, forgot those needed to be changed also 😅 they were set to an absolute path to have things working when i was writing them up, but i also use a relative path to load the data in the main doc (`class8.qmd`) -- i think once the location of the additional files is decided then all the paths in the `example` docs can be changed to that.

**Comment by lhe2** [comment]
rewrote `example-*.qmd` scripts to be a bit more general now, and also hopefully should run on everyone's computers! (so long as the path to the data in the repo doesnt change)

**Comment by jtlandis** [comment]
Everything looks good. 

To complete the last bullet point, what were you having in mind? Do you mean putting the data somewhere on longleaf? or just putting a link to the github location?

**Comment by lhe2** [comment]
keeping everything on the repo is fine with me! i assume the main file structure of this wont really change anymore, so i'll just direct them to the folder and they can futz around :P

**Comment by jtlandis** [comment]
@teresa-mcgee Has the repo been configured to automatically update the github pages? I dont want to merge and mess things up.

**Pull request merged**
